services:
  - type: web
    name: saleor-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saleor-db
          property: connectionString
      - key: REDIS_URL
        value: redis://red-d00fjcpr0fns73e7uq0g:6379
      - key: SECRET_KEY
        generateValue: true
